import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { LicenseData } from "./api/license";

export const generateLicensePDF = (data: LicenseData) => {
    const doc = new jsPDF();

    // Define colors
    const primaryColor = [33, 150, 243] as [number, number, number]; // Blue
    const dangerColor = [244, 67, 54] as [number, number, number]; // Red
    const successColor = [76, 175, 80] as [number, number, number]; // Green
    const warningColor = [255, 152, 0] as [number, number, number]; // Orange
    const textColor = [60, 60, 60] as [number, number, number]; // Dark Gray

    // Helper for status text
    const getStatusText = (value: boolean | string) => {
        if (value === true || value === "yes") return "Yes";
        if (value === false || value === "no") return "No";
        return "Conditional";
    };

    // Header Background
    doc.setFillColor(15, 23, 42); // Dark background
    doc.rect(0, 0, 210, 40, "F");

    // Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(255, 255, 255);
    doc.text("License Analysis Report", 105, 20, { align: "center" });

    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`Generated by CLicense on ${new Date().toLocaleDateString()}`, 105, 30, { align: "center" });

    // Reset Text Color
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);

    let yPos = 55;

    // License Overview
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("License Overview", 14, yPos);

    yPos += 10;
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    // License Name - Wrapped
    const namePrefix = "License Name: ";
    const nameWidth = 180; // Max width for content
    const splitName = doc.splitTextToSize(`${namePrefix}${data.licenseName}`, nameWidth);
    doc.text(splitName, 14, yPos);
    yPos += splitName.length * 7;

    // Source URL - Wrapped
    const urlPrefix = "Source URL: ";
    const splitUrl = doc.splitTextToSize(`${urlPrefix}${data.url}`, nameWidth);
    doc.text(splitUrl, 14, yPos);
    yPos += splitUrl.length * 7;

    // Verdict Badge Logic
    yPos += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Verdict: ", 14, yPos);

    let verdictColor = primaryColor;
    if (data.verdictType === 'safe') verdictColor = successColor;
    if (data.verdictType === 'warning') verdictColor = warningColor;
    if (data.verdictType === 'danger') verdictColor = dangerColor;

    doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
    const splitVerdict = doc.splitTextToSize(data.verdict, 150); // Wrap verdict text if long
    doc.text(splitVerdict, 35, yPos);
    doc.setTextColor(textColor[0], textColor[1], textColor[2]); // Reset

    yPos += Math.max(15, splitVerdict.length * 7 + 5);

    // Permissions Table
    autoTable(doc, {
        startY: yPos,
        head: [["Category", "Status"]],
        body: [
            ["Commercial Use", getStatusText(data.commercialUse)],
            ["Modification", getStatusText(data.modificationAllowed)],
            ["Redistribution", getStatusText(data.redistributionAllowed)],
        ],
        theme: 'grid',
        headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
        styles: { fontSize: 11, cellPadding: 8, overflow: 'linebreak' },
        columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } },
    });

    // @ts-ignore
    yPos = doc.lastAutoTable.finalY + 15;

    // Check for page break availability before Risks
    if (yPos > 250) {
        doc.addPage();
        yPos = 20;
    }

    // Key Risks Section
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Key Requirements & Risks", 14, yPos);
    yPos += 10;

    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");

    if (data.risks.length > 0) {
        data.risks.forEach((risk) => {
            const bullet = "• ";
            const riskText = doc.splitTextToSize(`${bullet}${risk}`, 180);

            // Page break check for each risk item
            if (yPos + riskText.length * 7 > 280) {
                doc.addPage();
                yPos = 20;
            }

            doc.text(riskText, 18, yPos);
            yPos += riskText.length * 7;
        });
    } else {
        doc.text("No specific risks detected.", 18, yPos);
    }

    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('CLicense - AI Powered License Analysis', 105, 290, { align: 'center' });
    }

    // Save PDF
    doc.save(`${data.licenseName.replace(/\s+/g, '_')}_Report.pdf`);
};
